{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lat-hva-team-json-be.fullname" . }}
  labels:
    {{- include "lat-hva-team-json-be.labels" . | nindent 4 }}
data:
  SCRIPT_FILENAME: "/var/www/html/public/index.php"
{{- end }}
